### ISSUE TITLE
[Feature Request]: Add Github Action to test the docker build

### ISSUE THREAD

**Issue by bamr87** [bamr87/barodybroject#63]
A request (2025-03-26) for a GitHub Action that builds the Docker image in CI, so that build errors seen locally during `azd build` surface automatically. **This has since been implemented.** `ci.yml` now carries two unconditional container jobs that build the exact image `azd build` produces, on every push and pull request. The remaining question is whether to close this as done or narrow it to literal `azd`-level coverage — see *Blocked on*.

## Context

The motivating problem was local-only failures: *"Local errors when running azd build."* Without CI coverage, a Dockerfile or dependency break is found by whoever next runs a build by hand, which is the failure mode this asked to remove.

`azure.yaml` declares one service:

```yaml
services:
  src:
    project: src
    host: containerapp
    language: python
```

So `azd build` builds `src/Dockerfile` from the `src/` context. That is precisely what CI now does.

## Reproduction

Not a defect — no reproduction applies. The evidence run is reported below for completeness and **its `"reproduced": true` flag is a false positive** caused by a broken sandbox (see *Evidence caveat*); it says nothing about this repo.

The relevant verification was reading the current CI at `main` (`23ad0ad`, 2026-08-20).

**`.github/workflows/ci.yml` triggers — unconditional on every PR:**

```yaml
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
```

**`container-validation`** (L251–276) — matrix over `[python, jekyll]`, no `if:` gate:

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Validate Compose files
        run: bash .github/scripts/compose-validation.sh validate
      - name: Run Compose smoke test
        if: matrix.service == 'python'
        run: bash .github/scripts/compose-validation.sh smoke
      - name: Build and test service
        run: bash .github/scripts/compose-validation.sh build-service ${{ matrix.service }}
```

**`container-security`** (L278–308) — builds the production image and scans it:

```yaml
      - name: Build production image for scanning
        run: bash .github/scripts/compose-validation.sh build-production-image barodybroject:security-scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
```

**And `.github/scripts/compose-validation.sh:84` is the decisive line:**

```bash
    docker build --tag "$image_tag" -f src/Dockerfile src
```

That is the same Dockerfile and the same build context `azd build` uses for the `src` service. A `src/Dockerfile` break now fails CI before merge.

Both jobs are also required inputs to the `ci-summary` gate:

```yaml
    needs: [pre-checks, tests, e2e, quality, container-validation, container-security]
```

The CI shell scripts were extracted in `e41f463` *"refactor: consolidate workflows and extract CI shell scripts"* (2026-04-27); the container jobs are present and active at `main` today.

### What is *not* covered

`azd` itself runs only in `deploy.yml` (`Azure/setup-azd@v2.4.0`, L86), which fires on successful CI on `main` or manual dispatch. Per `.github/workflows/README.md`, that is deliberate — *"Only workflow that should run `azd provision` or `azd deploy`."* So the `azd` CLI wrapper (`azd package`) is never exercised as a pure build check. For a `containerapp` service that wrapper is a thin layer over the same `docker build`, so the coverage gap is narrow but not empty: azd-specific tag/registry conventions and `azure.yaml` schema errors would not be caught by the docker build alone.

### Environment

| key | value |
| --- | --- |
| repo | `bamr87/barodybroject` @ `main` `23ad0ad` (2026-08-20) |
| detected stack | python |
| runner | Linux 6.17.0-1022-azure x86_64 |
| captured | 2026-09-03 08:21 UTC |
| python3 | 3.12.3 |

### Evidence caveat

The sandbox recorded `python-test` / `python-lint` as **fail (exit 127)** while `python-venv` / `python-install` passed. All four are artifacts of a virtualenv that was never created:

```console
$ .venv/bin/python -m pytest -q
bash: line 1: .../.venv/bin/python: No such file or directory
```

`exit 127` is command-not-found. **No conclusion about this repo's test or lint health follows from this bundle**, and `"reproduced": true` is incorrect. This is a `tools/issue-evidence.sh` defect, flagged in the intake comment.

## Expected vs actual

- **Expected (at filing, 2025-03-26):** CI builds the Docker image and fails on build errors.
- **Actual (today):** CI does exactly that, in two jobs, on every push and PR to `main`/`develop`, including a Trivy scan of the production image. The request is satisfied.
- **Residual gap:** the `azd` CLI build path (`azd package`) is exercised only inside `deploy.yml`, never as a standalone pre-merge check.

## Scope

**No change required for the request as written** — it is implemented.

If the residual gap is worth closing, the change would be confined to:

| file | why |
| --- | --- |
| `.github/workflows/ci.yml` | Add an `azd package`–based validation step, most naturally to `container-validation`. |
| `.github/scripts/compose-validation.sh` | Where the build commands live; a new subcommand would go here beside `build-production-image`. |
| `.github/workflows/README.md` | Documents the rule that only `deploy.yml` runs `azd`. Adding a build-only `azd` step to `ci.yml` needs that rule amended, or it will read as a violation. |

## Acceptance criteria

If closed as **already implemented** (recommended), verification is:

- [ ] `.github/workflows/ci.yml` contains `container-validation` and `container-security` with no `if:` gate suppressing them on pull requests. *(Verified at `23ad0ad`.)*
- [ ] `.github/scripts/compose-validation.sh` builds `src/Dockerfile` — the image `azure.yaml` maps to the `src` service. *(Verified: L84.)*
- [ ] Both jobs appear in `ci-summary`'s `needs:`, so a container build failure blocks the CI summary. *(Verified.)*
- [ ] A deliberately broken `src/Dockerfile` on a scratch branch fails CI. *(Not run — this is the one check that would confirm the wiring end to end rather than by inspection.)*

If instead the **azd gap** is to be closed:

- [ ] `azd package` (or equivalent) runs in CI on pull requests without requiring Azure credentials or performing any deployment.
- [ ] It fails CI when `azure.yaml` is malformed or its service mapping does not resolve — the class of error a bare `docker build` cannot catch.
- [ ] `.github/workflows/README.md`'s "only `deploy.yml` runs azd" rule is updated to permit the build-only invocation.
- [ ] No Azure secrets are added to a pull-request-triggered workflow.

## Blocked on

> **The feature as requested is implemented. Close as completed, or keep this open narrowed to the `azd package` coverage gap?**

| # | option | consequence |
| --- | --- | --- |
| **a** | Close as completed, referencing the container jobs. | Correct for the request as written. |
| **b** | Close, and open a new, narrowly-scoped issue for `azd package` in CI. | Keeps history honest — the new work is not what this asked for. |
| **c** | Keep open, re-scoped to the azd gap. | Retains a 521-day-old issue whose title no longer matches its content. |

**Recommendation: (a)**, or **(b)** if the azd-level check is genuinely wanted. The request was "test the docker build process using GitHub Actions to identify errors", and that is done — including a vulnerability scan nobody asked for. Re-scoping a stale issue to different work (c) makes it harder to read later, and the `azd` step needs its own justification against the README rule it would breach.

## References

- [`.github/workflows/ci.yml`](https://github.com/bamr87/barodybroject/blob/main/.github/workflows/ci.yml) — `container-validation` L251–276, `container-security` L278–308
- [`.github/scripts/compose-validation.sh`](https://github.com/bamr87/barodybroject/blob/main/.github/scripts/compose-validation.sh) — L84, `docker build -f src/Dockerfile src`
- [`.github/workflows/README.md`](https://github.com/bamr87/barodybroject/blob/main/.github/workflows/README.md) — the "only `deploy.yml` runs azd" rule
- [`azure.yaml`](https://github.com/bamr87/barodybroject/blob/main/azure.yaml) — the `src` → `containerapp` service mapping
- `e41f463` — "refactor: consolidate workflows and extract CI shell scripts" (2026-04-27), which extracted the container build scripts
- [Azure Developer CLI: `azd package`](https://learn.microsoft.com/azure/developer/azure-developer-cli/reference#azd-package)

---

<details><summary>Original report by @bamr87</summary>

## Describe your feature request clearly.

**Is your feature request related to a problem? Please describe.**

Need to test the docker build process using Github actions to identify errors 

**Describe the solution you'd like**

Local errors when running azd build.

</details>
